development:
  tunnel:
    public_host_username: mtodd@cloverhound.com
    public_host: tunnlr4258@ssh1.tunnlr.com
    public_port: 13296
    local_port: 3000 #or whatever port your rails server is running locally
    server_alive_interval: 0